name: report

on:
  workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
    - name: calc deployment frequency
      run: |
        gh api -X GET /repos/kekimura/mysample/deployments -f environment=Production >> $GIHUB_STEPS_SUMMARY
