name: report

on:
  workflow_dispatch

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
    - name: calc deployment frequency
      run: |
        $deploytimes = (gh api -X GET /repos/kekimura/mysample/deployments -f environment=Production -q '. | length')
        echo "DeployFrequency: ${deploytimes}" >> $GITHUB_STEP_SUMMARY
